services:
  db:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5433:5432"
    volumes:
      - ./prisma/postgres-data:/var/lib/postgresql/data
    user: "${UID}:${GID}"
    restart: always
